# Shells
sh=reverse_shell_detected
bash=reverse_shell_detected

# Exfiltration & Network
curl=suspicious_outbound_traffic
wget=suspicious_outbound_traffic
nc=nc_execution
tcpdump=network_sniffing

# Database Specific Dumps
pg_dump=unauthorized_database_dump
mysqldump=unauthorized_database_dump

# Files
/etc/passwd=unauthorized_file_read
/etc/shadow=unauthorized_file_read
/var/lib/postgresql/data/pg_hba.conf=database_config_tampering
