# Standard Shells
sh=reverse_shell_detected
bash=reverse_shell_detected
zsh=reverse_shell_detected
ash=reverse_shell_detected

# System Utilities & Package Managers
apt=unauthorized_package_installation
apt-get=unauthorized_package_installation
apk=unauthorized_package_installation
dpkg=unauthorized_package_installation

# Compilers (Catching on-the-fly exploit compilation)
gcc=unauthorized_compiler_usage
g++=unauthorized_compiler_usage
make=unauthorized_compiler_usage

# Privilege & Escapes
sudo=privilege_escalation
su=privilege_escalation
nsenter=container_escape_attempt
chroot=container_escape_attempt
unshare=container_escape_attempt

# Sensitive Files & Memory
/etc/shadow=unauthorized_file_read
/dev/mem=memory_dump_attempt
/dev/kmem=memory_dump_attempt
id_rsa=ssh_key_access
