# Kubernetes Binaries
kubectl=unauthorized_kubectl_execution
kubelet=unauthorized_kubelet_manipulation
etcdctl=etcd_database_manipulation

# Network Mapping
nmap=nmap_scan_detected
tshark=network_sniffing

# Core K8s Secrets
/etc/kubernetes/admin.conf=k8s_admin_config_access
/etc/kubernetes/pki/ca.key=k8s_ca_key_access
/etc/kubernetes/pki/apiserver.key=k8s_apiserver_key_access
/run/secrets/kubernetes.io/serviceaccount/token=k8s_token_theft
