# The Absolute Worst Offenders
nc=nc_execution
xmrig=crypto_miner_execution
nsenter=container_escape_attempt
/etc/shadow=unauthorized_file_read
/run/secrets/kubernetes.io/serviceaccount/token=k8s_token_theft
