replicaCount: 1

image:
  repository: auranet/controller
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  # Setting limits to prevent PyTorch from eating the whole node
  limits:
    memory: "1024Mi"
    cpu: "1000m"
  requests:
    memory: "512Mi"
    cpu: "250m"


genesisWeightsPath: ""

# Dynamic Application Configuration (Injects as ConfigMap Volume)
# These values are actively monitored by the Python watchdog for hot-reloading.
appConfig:
  fl_rounds: "1000"
  min_available_clients: "2"
  fraction_fit: "1.0"
  round_timeout_seconds: "600"
  proximal_mu: "0.1"