apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auranet-runtime-role
  labels:
    app: auranet-runtime
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]