apiVersion: v1
kind: ConfigMap
metadata:
  name: auranet-runtime-config
  namespace: auranet-namespace
  labels:
    app: auranet-runtime
data:
  # This mounts exactly as a file named THREAT_MAP.conf
  THREAT_MAP.conf: |
{{ .Values.runtime.threatMapConf | indent 4 }}