
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
  namespace: {{ .Values.namespace }}
rules:
  # Permission to cycle compromised pods
  - apiGroups: [""]
    resources: ["pods"]
    # deletecollection is required for the specific API call we used
    verbs: ["get", "list", "delete", "deletecollection"] 
    
  # Permission to manage Cilium Network Policies (Virtual Patches & Quarantines)
  - apiGroups: ["cilium.io"]
    resources: ["ciliumnetworkpolicies"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
  - apiGroups: ["cilium.io"]

    resources: ["tracingpolicies", "tracingpoliciesnamespaced"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]

---
# 2. Bind those permissions to our ServiceAccount (The RoleBinding)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io