# frontend -> gateway
#1. frontend-ui -> api-gateway:8080

# gateway -> backends
#2. api-gateway -> account-service:5000
#3. api-gateway -> loan-service:8080

# backends -> DB
#4. account-service -> finance-db:5432
#5. loan-service -> finance-db:5432
# public-gateway (Attacker/Entry) -> secure-vault (Target)
#1. public-gateway -> secure-vault:80
demo-gateway -> vulnerable-app:3000