apiVersion: v1
kind: Pod
metadata:
  name: auranet-runtime-test
  namespace: default
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet # <-- ADD THIS LINE
  containers:
  - name: forwarder
    image: auranet/runtime:v1
    imagePullPolicy: Never
    env:
    - name: LOG_PATH
      value: /var/run/cilium/tetragon/tetragon.log
    - name: NATS_URL
      value: nats://auranet-nats-broker.auranet-messaging.svc.cluster.local:4222
    volumeMounts:
    - name: tetragon-logs
      mountPath: /var/run/cilium/tetragon
      readOnly: true
  volumes:
  - name: tetragon-logs
    hostPath:
      path: /var/run/cilium/tetragon
      type: DirectoryOrCreate
