apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auranet-controller
  template:
    metadata:
      labels:
        app: auranet-controller
    spec:
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: grpc
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
