/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SystemNode, CommitLog } from './types';

export const INITIAL_NODES: SystemNode[] = [
  {
    id: 'central-hub',
    label: 'Central Hub',
    type: 'central',
    status: 'active',
    latency: 1.2,
    region: 'Central Gateway (UTC)',
    ip: '10.0.0.1',
    cpu: 48,
    memory: 62,
    connections: ['node-eu', 'node-us-east', 'node-ap', 'node-sa', 'node-af', 'node-us-west', 'node-eu-east', 'node-ap-east', 'node-oc', 'node-me', 'node-ca-central'],
  },
  {
    id: 'node-eu',
    label: 'EU West Gateway',
    type: 'gateway',
    status: 'active',
    latency: 18,
    region: 'Europe (London)',
    ip: '192.168.1.12',
    cpu: 72,
    memory: 55,
    connections: ['central-hub'],
  },
  {
    id: 'node-us-east',
    label: 'US East Compute',
    type: 'compute',
    status: 'active',
    latency: 24,
    region: 'North America (N. Virginia)',
    ip: '192.168.1.45',
    cpu: 85,
    memory: 79,
    connections: ['central-hub'],
  },
  {
    id: 'node-ap',
    label: 'Asia South Sensor',
    type: 'sensor',
    status: 'warning',
    latency: 92,
    region: 'Asia Pacific (Mumbai)',
    ip: '192.168.2.110',
    cpu: 94,
    memory: 40,
    connections: ['central-hub'],
  },
  {
    id: 'node-sa',
    label: 'South America Node',
    type: 'compute',
    status: 'active',
    latency: 45,
    region: 'South America (São Paulo)',
    ip: '192.168.3.4',
    cpu: 31,
    memory: 22,
    connections: ['central-hub'],
  },
  {
    id: 'node-af',
    label: 'Africa South Node',
    type: 'compute',
    status: 'offline',
    latency: 320,
    region: 'Africa (Cape Town)',
    ip: '192.168.4.15',
    cpu: 0,
    memory: 0,
    connections: ['central-hub'],
  },
  {
    id: 'node-us-west',
    label: 'US West Edge Gateway',
    type: 'gateway',
    status: 'active',
    latency: 14,
    region: 'US West (Oregon)',
    ip: '192.168.1.80',
    cpu: 58,
    memory: 42,
    connections: ['central-hub'],
  },
  {
    id: 'node-eu-east',
    label: 'EU East Gateway',
    type: 'gateway',
    status: 'active',
    latency: 32,
    region: 'Europe (Frankfurt)',
    ip: '192.168.1.95',
    cpu: 45,
    memory: 61,
    connections: ['central-hub'],
  },
  {
    id: 'node-ap-east',
    label: 'Asia East Compute',
    type: 'compute',
    status: 'active',
    latency: 55,
    region: 'Asia Pacific (Tokyo)',
    ip: '192.168.2.215',
    cpu: 67,
    memory: 73,
    connections: ['central-hub'],
  },
  {
    id: 'node-oc',
    label: 'Oceania Beacon',
    type: 'sensor',
    status: 'active',
    latency: 110,
    region: 'Oceania (Sydney)',
    ip: '192.168.5.12',
    cpu: 28,
    memory: 34,
    connections: ['central-hub'],
  },
  {
    id: 'node-me',
    label: 'Middle East Sensor',
    type: 'sensor',
    status: 'active',
    latency: 78,
    region: 'Middle East (Dubai)',
    ip: '192.168.6.50',
    cpu: 49,
    memory: 52,
    connections: ['central-hub'],
  },
  {
    id: 'node-ca-central',
    label: 'Canada Central Node',
    type: 'compute',
    status: 'active',
    latency: 21,
    region: 'Canada (Montreal)',
    ip: '192.168.1.200',
    cpu: 39,
    memory: 44,
    connections: ['central-hub'],
  },
];

export const INITIAL_COMMITS: CommitLog[] = [
  {
    id: 'c1',
    author: 'Emily Rose',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    timeAgo: '2h ago',
    message: 'Updated main visualizer logic to handle large datasets more efficiently without frame drops.',
    nodeId: 'central-hub',
    category: 'logic',
  },
  {
    id: 'c2',
    author: 'Mateo Clea',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    timeAgo: '5h ago',
    message: 'Patched security vulnerability in the node authentication module.',
    nodeId: 'node-eu',
    category: 'security',
  },
  {
    id: 'c3',
    author: 'Emily Rose',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    timeAgo: '1d ago',
    message: 'Refactored state sync engine to optimize memory consumption under peak workloads.',
    nodeId: 'node-us-east',
    category: 'performance',
  },
  {
    id: 'c4',
    author: 'System Operator',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=150',
    timeAgo: '2d ago',
    message: 'Provisioned South America Gateway with automated scaling configuration.',
    nodeId: 'node-sa',
    category: 'infra',
  },
];

export const USER_PROFILE = {
  name: 'Emily Rose',
  role: 'Senior Network Architect',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
  email: 'emily.rose@projectalpha.io',
  bio: 'Specialist in distributed consensus algorithms, high-throughput stream processing, and mesh network optimization. Graduated in Computer Engineering (2024).',
};
