apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: auranet-block-log4shell
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      role: backend-api
  ingress:
  - toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
      rules:
        http:
        - method: ".*"
          path: ".*(?i)(\\$\\{jndi:).*"
