apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: auranet-prevent-scanners
  namespace: default
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    selectors:
    - matchArgs:
      - index: 0
        operator: "In"
        values:
        - "/usr/bin/nmap"
        - "/usr/bin/masscan"
      matchActions:
      - action: Sigkill
