apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: auranet-block-xss
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      role: frontend-web
  ingress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        # Theoretical regex matching XSS payloads
        - method: ".*"
          path: ".*(?i)(<script>|javascript:|onerror=|onload=|<img.*src=).*"
