import subprocess
import time
import random

def get_pod_name(app_label, namespace="default"):
    """Dynamically fetches the exact pod name generated by the Deployment."""
    cmd = f"kubectl get pods -n {namespace} -l app={app_label} -o jsonpath='{{.items[0].metadata.name}}'"
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return result.stdout.strip()

def run_curl(source_pod, target_svc, port, path, method="GET", namespace="default"):
    """Executes a curl command from inside a specific pod."""
    cmd = f"kubectl exec -n {namespace} {source_pod} -- curl -s -X {method} http://{target_svc}:{port}{path}"
    subprocess.run(cmd, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print(f"[{source_pod}] -> {method} http://{target_svc}:{port}{path}")

def generate_traffic():
    print("🐝 Initializing AuraNet Traffic Simulator...")
    
    # Get dynamic pod names
    retail_pod = get_pod_name("retail-dashboard")
    invest_pod = get_pod_name("investment-dashboard")
    
    if not retail_pod or not invest_pod:
        print("❌ Error: Could not find pods. Are the sample workloads running?")
        return

    print("\n--- PHASE 1: Generating Benign Baseline (Normal Traffic) ---")
    print("Simulating authorized retail traffic for 30 seconds...")
    for _ in range(15):
        # Normal, expected behavior
        run_curl(retail_pod, "customer-api", 8000, "/health")
        time.sleep(random.uniform(0.5, 2.0))

    print("\n--- PHASE 2: Generating Layer 3/4 Anomalies (Unauthorized Access) ---")
    print("Simulating investment-dashboard attempting to breach the API (Will be DROPPED by Cilium/SPIRE)...")
    for _ in range(5):
        # This will fail the mTLS/Network Policy check, but Hubble will log the DROP
        run_curl(invest_pod, "customer-api", 8000, "/health")
        time.sleep(1)

    print("\n--- PHASE 3: Generating Layer 7 Anomalies (Insider Threat/Compromise) ---")
    print("Simulating a compromised retail-dashboard sending malicious L7 payloads...")
    malicious_paths = [
        "/admin/delete",                  # Privilege Escalation attempt
        "/health?user=1'%20OR%20'1'='1",  # SQL Injection attempt
        "/etc/passwd",                    # Path Traversal attempt
    ]
    
    for _ in range(10):
        path = random.choice(malicious_paths)
        # Using a forbidden HTTP method (POST instead of GET)
        method = random.choice(["GET", "POST", "DELETE"])
        run_curl(retail_pod, "customer-api", 8000, path, method)
        time.sleep(1)

    print("\n✅ Traffic generation complete! The network telemetry is now in Hubble.")

if __name__ == "__main__":
    generate_traffic()
