import subprocess
import time
import random

def get_pod_name(app_label, namespace="default"):
    """Dynamically fetches the exact pod name generated by the Deployment."""
    cmd = f"kubectl get pods -n {namespace} -l app={app_label} -o jsonpath='{{.items[0].metadata.name}}'"
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return result.stdout.strip()

def run_curl(source_pod, target_svc, port, path, method="GET", timeout=1):
    """Executes a curl command from inside a specific pod."""
    # ADDED DOUBLE QUOTES AROUND THE URL TO PREVENT BASH SHELL INJECTION ERRORS
    cmd = f"kubectl exec -n default {source_pod} -- curl -s -o /dev/null -w '%{{http_code}}' -X {method} --max-time {timeout} \"http://{target_svc}:{port}{path}\""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    print(f"[{source_pod}] -> {method} http://{target_svc}:{port}{path} (HTTP {result.stdout})")

def generate_traffic():
    print("🐝 Initializing AuraNet Context-Aware Traffic Simulator...")
    
    retail_pod = get_pod_name("retail-dashboard")
    invest_pod = get_pod_name("investment-dashboard")
    
    if not retail_pod or not invest_pod:
        print("❌ Error: Could not find pods. Are the sample workloads running?")
        return

    print("\n--- PHASE 0: SPIRE mTLS Tunnel Warm-up ---")
    print("Sending an initial request with a 5-second timeout to allow the TLS handshake to complete...")
    run_curl(retail_pod, "customer-api", 8000, "/health", timeout=5)
    time.sleep(1) # Let the network settle

    print("\n--- PHASE 1: Benign Baseline (Retail fetching Customer Data) ---")
    print("Simulating authorized retail traffic to /customers/{id} (Will SUCCEED)...")
    for _ in range(25):
        customer_id = random.randint(1, 25)
        run_curl(retail_pod, "customer-api", 8000, f"/customers/{customer_id}")
        time.sleep(random.uniform(0.2, 1.0))

    print("\n--- PHASE 2: Boundary Enforcement (Benign app, unauthorized path) ---")
    print("Simulating Investment Dashboard attempting to reach Customer API (Will DROP)...")
    for _ in range(10):
        customer_id = random.randint(1, 25)
        run_curl(invest_pod, "customer-api", 8000, f"/customers/{customer_id}")
        time.sleep(0.5)

    print("\n--- PHASE 3: L7 Anomalies (Insider Threat / API Abuse) ---")
    print("Simulating a compromised Retail Dashboard manipulating HTTP verbs & endpoints...")
    
    l7_attacks = [
        {"path": "/customers/1", "method": "POST"},
        {"path": "/customers/1", "method": "DELETE"},
        {"path": "/customers/admin_dump", "method": "GET"},
        {"path": "/customers/1'%20OR%201=1", "method": "GET"},
    ]
    
    for _ in range(10):
        attack = random.choice(l7_attacks)
        run_curl(retail_pod, "customer-api", 8000, attack["path"], attack["method"])
        time.sleep(0.5)

    print("\n✅ Context-aware traffic generation complete! Data is ready in Hubble.")

if __name__ == "__main__":
    generate_traffic()