apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: oqs-istio-control-plane
  namespace: istio-system
spec:
  hub: docker.io/openquantumsafe
  tag: 1.18.0-oqs  # The OQS fork version
  
  components:
    base:
      enabled: true
    pilot:
      enabled: true
  
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # PQC KEMs are only supported in TLS 1.3
        # tired 1.2 and earlier versions
        TLS_MAX_VERSION: "TLSv1_3"
        TLS_MIN_VERSION: "TLSv1_3"
